name: CI

on: issue_comment

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/tags/cc
    - name: Run a one-line script
      run: echo Hello, world!
