name: CI

on:
   schedule:
    - cron:  '*/3 * * * *'
      
jobs:
  build:
    strategy:
      matrix:
        refs: [refs/heads/master, refs/tags/cc, refs/tags/dd]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ matrix.refs }}
    - name: Run a one-line script
      run: cat 1.txt
