name: CI

on:
  pull_request:
    types: [opened, synchronized]
  push:
    branches:
      - staging
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
