name: docker

on: [push]
      
jobs:
  build:
    strategy:
      matrix:
        refs: [refs/heads/master, refs/tags/tag1, refs/tags/tag2]

    runs-on: ubuntu-latest
    env:
       gitrefs: ${{ matrix.refs }} 
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ matrix.refs }}
    - name: build docker image
      run: echo %gitrefs%
